### ISSUE TITLE
Audio analysis

### ISSUE THREAD

**Issue by MattiaRiola** [MattiaRiola/iv4xrDemo#3]
# Analyse audio

## Suppositions

Let's suppose each audio has this format:
- sample rate = 44.1kHz
- sample size = 16bit
- channels = 1
- extension = .wav

### Text similarity testing

- [wav2vec](https://arxiv.org/abs/2006.11477)

#### Polt the spectrum and time domain audio signal

To plot the spectrum AudioAnalyzer is imported though it didn't work until I installed the correct versions of Python packages used in RiverGame.
- [x] Time domain audio
- [x] spectrum

#### Java implementation audio recognition using FFT match score
- [src](https://www.royvanrijn.com/blog/2010/06/creating-shazam-in-java/)
   - FFT lib used:
     - [StdRandom](https://introcs.cs.princeton.edu/java/32class/StdRandom.java)
     - [FFT](https://introcs.cs.princeton.edu/java/32class/FFT.java)
     - [Complex](https://introcs.cs.princeton.edu/java/32class/Complex.java)
- [link1](https://www.toptal.com/algorithms/shazam-it-music-processing-fingerprinting-and-recognition#:~:text=The%20Shazam%20algorithm%20distills%20samples,each%20other%20within%20a%20song.)

#### Database creation

Create a database with the fingerprint of every sound asset

#### Hash collision handling

Instead of using Map<Hash, ChunkDetail> where the chunkDetail contains the detail of the chunk (time, sampleIndex, hash, songName). This is problematic for different chunks with the same hash (i.e. chunk of the song1 at 3 seconds has the same hash as the chunk of the song2 at 5 seconds).

After a change in the data model, a List of chunkDetails is associated with a single hash. This way, when a collision is found, the chunk is added to the list instead of overwriting the previous one.
During the match phase, if the analysed audio has a match, every chunk with that match will be considered in that match for that second.

#### ⚠️ Problems

This method works fine with music but it has some problems with short sounds,
I've tried to modify CHUNK_SIZE and FUZ_FACTOR but the results are unpredictable

### Neural network
Another way to recognize sounds in a game is using a neural network.

- [Audio classification using neural network](https://towardsdatascience.com/audio-deep-learning-made-simple-sound-classification-step-by-step-cebc936bbe5)

**Comment by MattiaRiola** [comment]
When I try to plot the spectrum I get this error:

```
Traceback (most recent call last):
  File "iv4xrDemo\src\test\python\audio_comparator.py", line 4, in <module>
    original.plot_spectrum(min_freq=20, max_freq=1000, title="1965 Original")
  File "iv4xrDemo\src\test\python\AudioAnalyzer.py", line 76, in plot_spectrum
    window.plot(x='bins', y='scaled_amplitude', figsize=(16,4))
  File "RiverGame\game-testing\venv\Lib\site-packages\pandas\plotting\_core.py", line 975, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "RiverGame\game-testing\venv\Lib\site-packages\pandas\plotting\_matplotlib\__init__.py", line 71, in plot
    plot_obj.generate()
  File "RiverGame\game-testing\venv\Lib\site-packages\pandas\plotting\_matplotlib\core.py", line 447, in generate
    self._setup_subplots()
  File "RiverGame\game-testing\venv\Lib\site-packages\pandas\plotting\_matplotlib\core.py", line 510, in _setup_subplots
    axes = fig.add_subplot(111)
           ^^^^^^^^^^^^^^^^^^^^
  File "RiverGame\game-testing\venv\Lib\site-packages\matplotlib\figure.py", line 739, in add_subplot
    and isinstance(args[0], mpl.axes._base._AxesBase)
                            ^^^^^^^^
  File "RiverGame\game-testing\venv\Lib\site-packages\matplotlib\_api\__init__.py", line 226, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib' has no attribute 'axes'. Did you mean: 'axis'?
```

**Comment by MattiaRiola** [comment]
Useful links to solve the problem:

- [importing plot correctly](https://www.datasciencelearner.com/module-matplotlib-has-no-attribute-plot-solved-attributeerror/)
- [pandas data frame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.html)

**Comment by MattiaRiola** [comment]
[reading wav file](https://stackoverflow.com/questions/27517265/graphing-wav-file-in-java)
